In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('CC GENERAL.csv')

In [3]:
df.head()

CUST_ID      BALANCE  BALANCE_FREQUENCY  PURCHASES  ONEOFF_PURCHASES  \
0  C10001    40.900749           0.818182      95.40              0.00   
1  C10002  3202.467416           0.909091       0.00              0.00   
2  C10003  2495.148862           1.000000     773.17            773.17   
3  C10004  1666.670542           0.636364    1499.00           1499.00   
4  C10005   817.714335           1.000000      16.00             16.00   

   INSTALLMENTS_PURCHASES  CASH_ADVANCE  PURCHASES_FREQUENCY  \
0                    95.4      0.000000             0.166667   
1                     0.0   6442.945483             0.000000   
2                     0.0      0.000000             1.000000   
3                     0.0    205.788017             0.083333   
4                     0.0      0.000000             0.083333   

   ONEOFF_PURCHASES_FREQUENCY  PURCHASES_INSTALLMENTS_FREQUENCY  \
0                    0.000000                          0.083333   
1                    0.000000                          0.000000   
2                    1.000000                          0.000000   
3                    0.083333                          0.000000   
4                    0.083333                          0.000000   

   CASH_ADVANCE_FREQUENCY  CASH_ADVANCE_TRX  PURCHASES_TRX  CREDIT_LIMIT  \
0                0.000000                 0              2        1000.0   
1                0.250000                 4              0        7000.0   
2                0.000000                 0             12        7500.0   
3                0.083333                 1              1        7500.0   
4                0.000000                 0              1        1200.0   

      PAYMENTS  MINIMUM_PAYMENTS  PRC_FULL_PAYMENT  TENURE  
0   201.802084        139.509787          0.000000      12  
1  4103.032597       1072.340217          0.222222      12  
2   622.066742        627.284787          0.000000      12  
3     0.000000               NaN          0.000000      12  
4   678.334763        244.791237          0.000000      12

##### CUSTID : Identification of Credit Card holder (Categorical)
##### BALANCE : Balance amount left in their account to make purchases (
##### BALANCEFREQUENCY : How frequently the Balance is updated, score between 0 and 1 (1 = frequently updated, 0 = not frequently updated)
##### PURCHASES : Amount of purchases made from account
##### ONEOFFPURCHASES : Maximum purchase amount done in one-go
##### INSTALLMENTSPURCHASES : Amount of purchase done in installment
##### CASHADVANCE : Cash in advance given by the user
##### PURCHASESFREQUENCY : How frequently the Purchases are being made, score between 0 and 1 (1 = frequently purchased, 0 = not frequently purchased)
##### ONEOFFPURCHASESFREQUENCY : How frequently Purchases are happening in one-go (1 = frequently purchased, 0 = not frequently purchased)
##### PURCHASESINSTALLMENTSFREQUENCY : How frequently purchases in installments are being done (1 = frequently done, 0 = not frequently done)
##### CASHADVANCEFREQUENCY : How frequently the cash in advance being paid
##### CASHADVANCETRX : Number of Transactions made with "Cash in Advanced"
##### PURCHASESTRX : Numbe of purchase transactions made
##### CREDITLIMIT : Limit of Credit Card for user
##### PAYMENTS : Amount of Payment done by user
##### MINIMUM_PAYMENTS : Minimum amount of payments made by user
##### PRCFULLPAYMENT : Percent of full payment paid by user
##### TENURE : Tenure of credit card service for user

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8950 entries, 0 to 8949
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   CUST_ID                           8950 non-null   object 
 1   BALANCE                           8950 non-null   float64
 2   BALANCE_FREQUENCY                 8950 non-null   float64
 3   PURCHASES                         8950 non-null   float64
 4   ONEOFF_PURCHASES                  8950 non-null   float64
 5   INSTALLMENTS_PURCHASES            8950 non-null   float64
 6   CASH_ADVANCE                      8950 non-null   float64
 7   PURCHASES_FREQUENCY               8950 non-null   float64
 8   ONEOFF_PURCHASES_FREQUENCY        8950 non-null   float64
 9   PURCHASES_INSTALLMENTS_FREQUENCY  8950 non-null   float64
 10  CASH_ADVANCE_FREQUENCY            8950 non-null   float64
 11  CASH_ADVANCE_TRX                  8950 non-null   int64  
 12  PURCHA

In [26]:
df = df.dropna()

In [27]:
df = df[df.columns.difference(['CUST_ID'])]

In [28]:
df.describe()

BALANCE  BALANCE_FREQUENCY  CASH_ADVANCE  CASH_ADVANCE_FREQUENCY  \
count   8636.000000        8636.000000   8636.000000             8636.000000   
mean    1601.224893           0.895035    994.175523                0.137604   
std     2095.571300           0.207697   2121.458303                0.201791   
min        0.000000           0.000000      0.000000                0.000000   
25%      148.095189           0.909091      0.000000                0.000000   
50%      916.855459           1.000000      0.000000                0.000000   
75%     2105.195853           1.000000   1132.385490                0.250000   
max    19043.138560           1.000000  47137.211760                1.500000   

       CASH_ADVANCE_TRX  CREDIT_LIMIT  INSTALLMENTS_PURCHASES  \
count       8636.000000   8636.000000             8636.000000   
mean           3.313918   4522.091030              420.843533   
std            6.912506   3659.240379              917.245182   
min            0.000000     50.000000                0.000000   
25%            0.000000   1600.000000                0.000000   
50%            0.000000   3000.000000               94.785000   
75%            4.000000   6500.000000              484.147500   
max          123.000000  30000.000000            22500.000000   

       MINIMUM_PAYMENTS  ONEOFF_PURCHASES  ONEOFF_PURCHASES_FREQUENCY  \
count       8636.000000       8636.000000                 8636.000000   
mean         864.304943        604.901438                    0.205909   
std         2372.566350       1684.307803                    0.300054   
min            0.019163          0.000000                    0.000000   
25%          169.163545          0.000000                    0.000000   
50%          312.452292         44.995000                    0.083333   
75%          825.496463        599.100000                    0.333333   
max        76406.207520      40761.250000                    1.000000   

           PAYMENTS  PRC_FULL_PAYMENT     PURCHASES  PURCHASES_FREQUENCY  \
count   8636.000000       8636.000000   8636.000000          8636.000000   
mean    1784.478099          0.159304   1025.433874             0.496000   
std     2909.810090          0.296271   2167.107984             0.401273   
min        0.049513          0.000000      0.000000             0.000000   
25%      418.559237          0.000000     43.367500             0.083333   
50%      896.675701          0.000000    375.405000             0.500000   
75%     1951.142090          0.166667   1145.980000             0.916667   
max    50721.483360          1.000000  49039.570000             1.000000   

       PURCHASES_INSTALLMENTS_FREQUENCY  PURCHASES_TRX       TENURE  
count                       8636.000000    8636.000000  8636.000000  
mean                           0.368820      15.033233    11.534391  
std                            0.398093      25.180468     1.310984  
min                            0.000000       0.000000     6.000000  
25%                            0.000000       1.000000    12.000000  
50%                            0.166667       7.000000    12.000000  
75%                            0.750000      18.000000    12.000000  
max                            1.000000     358.000000    12.000000

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
df_log = np.log1p(df)

In [31]:
df_scaled = StandardScaler().fit_transform(df_log)

In [33]:
pd.DataFrame(df_scaled)

0         1         2         3         4         5         6   \
0    -1.334707 -0.270722 -0.937894 -0.731226 -0.817000 -1.448165  0.381976   
1     0.952729  0.115912  1.518315  0.681686  0.768516  0.917235 -1.096108   
2     0.821135  0.484556 -0.937894 -0.731226 -0.817000  1.001126 -1.096108   
3     0.233137  0.484556 -0.937894 -0.731226 -0.817000 -1.226644 -1.096108   
4     0.651839  0.484556 -0.937894 -0.731226 -0.817000 -0.733891  1.232117   
...        ...       ...       ...       ...       ...       ...       ...   
8631 -2.288300 -1.795159 -0.937894 -0.731226 -0.817000 -2.289894 -1.096108   
8632 -1.519916  0.484556 -0.937894 -0.731226 -0.817000 -1.448165  0.740669   
8633 -1.619945 -0.204961 -0.937894 -0.731226 -0.817000 -1.448165  0.514944   
8634 -1.895971 -0.204961  0.077508  0.244835  0.265283 -2.289894 -1.096108   
8635 -0.180530 -0.960236  0.420960  1.090332  0.265283 -1.226644 -1.096108   

            7         8         9         10        11        12        13  \
0    -0.821250 -0.996024 -0.740409 -1.295478 -0.569607 -0.123312 -0.761203   
1     0.887368 -0.996024 -0.740409  1.297354  0.367222 -1.686451 -1.317269   
2     0.437336  1.049151  2.440893 -0.327811 -0.569607  0.589495  1.183110   
3    -0.351329 -0.124918 -0.373042 -0.253271 -0.569607 -0.717052 -1.028534   
4     1.566464 -0.996024 -0.740409  0.370793 -0.569607  0.775749  0.525425   
...        ...       ...       ...       ...       ...       ...       ...   
8631 -1.787956 -0.047046 -0.032910 -2.350564 -0.569607 -0.630393 -0.761203   
8632 -1.691444 -0.996024 -0.740409 -0.884686  1.323304  0.256021  1.183110   
8633 -1.259409 -0.996024 -0.740409 -2.073298  0.472137  0.017308  0.869235   
8634 -1.583035 -0.996024 -0.740409 -2.443495  0.472137 -1.686451 -1.317269   
8635 -1.202259  1.155543  1.604102 -2.287581 -0.569607  0.707892  0.525425   

            14        15        16  
0    -0.684522 -0.593218  0.341778  
1    -0.968116 -1.390107  0.341778  
2    -0.968116  0.470403  0.341778  
3    -0.968116 -0.887326  0.341778  
4     0.660027  0.203671  0.341778  
...        ...       ...       ...  
8631 -0.968116 -0.887326 -4.512398  
8632  1.179449  0.021377 -4.512398  
8633  0.841762 -0.090437 -4.512398  
8634 -0.968116 -1.390107 -4.512398  
8635 -0.968116  0.915124 -4.512398  

[8636 rows x 17 columns]

##### Truncated SVD는 Sigma 행렬에 있는 대각원소 ,즉 특이값 중 상위 일부 데이터만 추출해 분해하는 방식이다.

##### 이렇게 분해하면 인위적으로 더 작은 차원의 U,∑, V^T를 분해하기 때문에 원본 행렬을 정확하게 원복할 수 없다.

##### 그러나 데이터 정보가 압축되어 분해됨에도 불구하고 상당한 수준으로 원본 행렬을 근사 할 수 있다.

참고 : https://ariz1623.tistory.com/219

In [18]:
from scipy.sparse.linalg import svds
from scipy.linalg import svd

# 원본 행렬을 출력하고, SVD를 적용할 경우 U, Sigma, Vt 의 차원 확인 
np.random.seed(121)
matrix = np.random.random((6, 6))
print('원본 행렬:\n',matrix)
U, Sigma, Vt = svd(matrix, full_matrices=False)
print('\n분해 행렬 차원:',U.shape, Sigma.shape, Vt.shape)
print('\nSigma값 행렬:', Sigma)

# Truncated SVD로 Sigma 행렬의 특이값을 4개로 하여 Truncated SVD 수행. 
num_components = 4
U_tr, Sigma_tr, Vt_tr = svds(matrix, k=num_components)
print('\nTruncated SVD 분해 행렬 차원:',U_tr.shape, Sigma_tr.shape, Vt_tr.shape)
print('\nTruncated SVD Sigma값 행렬:', Sigma_tr)
matrix_tr = np.dot(np.dot(U_tr,np.diag(Sigma_tr)), Vt_tr)  # output of TruncatedSVD

print('\nTruncated SVD로 분해 후 복원 행렬:\n', matrix_tr)

원본 행렬:
 [[0.11133083 0.21076757 0.23296249 0.15194456 0.83017814 0.40791941]
 [0.5557906  0.74552394 0.24849976 0.9686594  0.95268418 0.48984885]
 [0.01829731 0.85760612 0.40493829 0.62247394 0.29537149 0.92958852]
 [0.4056155  0.56730065 0.24575605 0.22573721 0.03827786 0.58098021]
 [0.82925331 0.77326256 0.94693849 0.73632338 0.67328275 0.74517176]
 [0.51161442 0.46920965 0.6439515  0.82081228 0.14548493 0.01806415]]

분해 행렬 차원: (6, 6) (6,) (6, 6)

Sigma값 행렬: [3.2535007  0.88116505 0.83865238 0.55463089 0.35834824 0.0349925 ]

Truncated SVD 분해 행렬 차원: (6, 4) (4,) (4, 6)

Truncated SVD Sigma값 행렬: [0.55463089 0.83865238 0.88116505 3.2535007 ]

Truncated SVD로 분해 후 복원 행렬:
 [[0.19222941 0.21792946 0.15951023 0.14084013 0.81641405 0.42533093]
 [0.44874275 0.72204422 0.34594106 0.99148577 0.96866325 0.4754868 ]
 [0.12656662 0.88860729 0.30625735 0.59517439 0.28036734 0.93961948]
 [0.23989012 0.51026588 0.39697353 0.27308905 0.05971563 0.57156395]
 [0.83806144 0.78847467 0.93868685 0.72673231 

In [36]:
from sklearn.decomposition import TruncatedSVD
import matplotlib.pyplot as plt

In [51]:
tsvd = TruncatedSVD(n_components = 6)
tsvd.fit(df_scaled)
df_svd = tsvd.transform(df_scaled)

In [53]:
sum(tsvd.explained_variance_ratio_)

0.8563432787809871

In [54]:
tsvd.explained_variance_ratio_

array([0.3473001 , 0.22415275, 0.09591753, 0.07681046, 0.06848134,
       0.04368109])

In [55]:
tsvd = TruncatedSVD(n_components = 4)
tsvd.fit(df_scaled)
df_svd = tsvd.transform(df_scaled)

In [56]:
sum(tsvd.explained_variance_ratio_)

0.7441808461212374

In [58]:
np.save('tsvd.npy', df_svd)